### ISSUE TITLE
Service account doesn't get permission to do anything

### ISSUE THREAD

**Issue by lukemarsden** [jbeda/kubeadm-gce-tf#4]
The README says to create a service account:
```
$ gcloud iam service-accounts --format='value(email)' create k8s-terraform
```
However, such a service account doesn't have permission to do anything.
I granted it permission using the web interface:
<img width="489" alt="screen shot 2016-10-31 at 09 35 24" src="https://cloud.githubusercontent.com/assets/264658/19849924/b50ba740-9f4d-11e6-85b6-f8a9cb8db7d6.png">
But it would be nice not to have to do that.
The [docs for IAM roles](https://cloud.google.com/iam/docs/granting-changing-revoking-access) suggest "Using a text editor, add a new object to the bindings array [...]", but maybe we can do some magick with `jq`.

**Comment by jbeda** [comment]
Shoot -- I did it from the UI and assumed it would be the same from the CLI.  I'll research how to give it the right role.
